name: GitHub Actions Practice

on:
  push:

jobs:
  Explorando-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Mostrar información del evento
        run: echo 'Evento que activó el workflow: ${{ github.event_name }}'

      - name: Mostrar información del runner
        run: echo "Sistema operativo del runner: ${{ runner.os }}"

      - name: Listar archivos
        run: ls -la
