name: Github Actions Practice

on: [push]

jobs:
  Explorando-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Mostrar informaci칩n del evento
        run: echo "El flujo de trabajo ha sido ejecutado en el evento: ${{ github.event_name }}"
      
      - name: Mostrar informaci칩n del runner
        run: echo "El trabajo se est치 ejecutado en un servidor ${{ runner.os }} hospedado en Github"
      
      - name: Verificar el c칩digo del repositorio
        uses: actions/checkout@v3
      
      - name: Listar archivos
        run: ls -la
