name: Mi Primer Workflow

on: [push]

jobs:
  mi-primer-job:
    runs-on: ubuntu-latest
    steps:
      - name: Paso 1 - Saludo
        run: echo "Â¡Hola! El workflow funciona ðŸŽ‰"
      
      - name: Paso 2 - InformaciÃ³n
        run: echo "Esto se ejecutÃ³ por: ${{ github.event_name }}"
